
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TH = 188;
  public static final int MIDDLE = 178;
  public static final int TD = 189;
  public static final int ALIGN = 171;
  public static final int BELOW = 159;
  public static final int H6 = 71;
  public static final int HEAD = 88;
  public static final int TITLE = 16;
  public static final int H5 = 70;
  public static final int ONMOUSEMOVE = 23;
  public static final int H4 = 69;
  public static final int H3 = 68;
  public static final int OPTGROUP = 152;
  public static final int H2 = 67;
  public static final int H1 = 66;
  public static final int SUMMARY = 190;
  public static final int OPEN_CLOSING_TAG = 4;
  public static final int CIRCLE = 9;
  public static final int NOSCRIPT = 64;
  public static final int VALUE = 120;
  public static final int HREF = 94;
  public static final int RPAREN = 208;
  public static final int OPEN_TAG = 2;
  public static final int FORM = 86;
  public static final int ONRESET = 132;
  public static final int ARCHIVE = 115;
  public static final int TIMES = 206;
  public static final int BORDER = 165;
  public static final int VSIDES = 163;
  public static final int HTTPEQUIV = 95;
  public static final int ONCLICK = 19;
  public static final int CAPTION = 181;
  public static final int BASELINE = 180;
  public static final int DOCTYPE = 7;
  public static final int STYLE = 14;
  public static final int AXIS = 197;
  public static final int STANDBY = 116;
  public static final int VALIGN = 176;
  public static final int ACCESSKEY = 28;
  public static final int UMINUS = 205;
  public static final int NONE = 166;
  public static final int CHECKED = 144;
  public static final int CLOSE_TAG = 3;
  public static final int CENTER = 173;
  public static final int RHS = 162;
  public static final int OPTION = 153;
  public static final int EM = 43;
  public static final int RADIO = 139;
  public static final int TYPE = 101;
  public static final int SCOPE = 199;
  public static final int COLSPAN = 201;
  public static final int DIV = 83;
  public static final int DIR = 18;
  public static final int LHS = 161;
  public static final int LABEL = 59;
  public static final int DT = 76;
  public static final int ROWS = 154;
  public static final int EOF = 0;
  public static final int COL = 186;
  public static final int KBD = 49;
  public static final int MINUS = 204;
  public static final int DL = 75;
  public static final int BIG = 41;
  public static final int INS = 61;
  public static final int BASE = 92;
  public static final int BLOCKQUOTE = 80;
  public static final int PARAM = 109;
  public static final int DD = 77;
  public static final int MAP = 35;
  public static final int VOID = 157;
  public static final int TEXTAREA = 58;
  public static final int METHOD = 129;
  public static final int BODY = 89;
  public static final int THEAD = 182;
  public static final int ACTION = 128;
  public static final int HIDDEN = 143;
  public static final int SIZE = 147;
  public static final int ONKEYPRESS = 25;
  public static final int SUBMIT = 140;
  public static final int COLGROUP = 185;
  public static final int CITE = 51;
  public static final int GROUPS = 167;
  public static final int SCRIPT = 63;
  public static final int CHAR = 169;
  public static final int NUMBER = 209;
  public static final int NAME = 96;
  public static final int HTML = 87;
  public static final int XML_LANG = 17;
  public static final int ONSUBMIT = 131;
  public static final int OL = 73;
  public static final int ONCHANGE = 150;
  public static final int IMG = 37;
  public static final int CLASSID = 111;
  public static final int CHECKBOX = 138;
  public static final int CONTENT = 97;
  public static final int SEMI = 202;
  public static final int REV = 103;
  public static final int CHAROFF = 170;
  public static final int BR = 32;
  public static final int SHAPE = 107;
  public static final int PASSWORD = 137;
  public static final int CHARSET = 99;
  public static final int PRE = 78;
  public static final int SAMP = 48;
  public static final int LEFT = 172;
  public static final int TABLE = 85;
  public static final int REL = 102;
  public static final int FIELDSET = 84;
  public static final int INPUT = 56;
  public static final int CELLPADDING = 194;
  public static final int RIGHT = 174;
  public static final int ONKEYDOWN = 26;
  public static final int DFN = 45;
  public static final int ONFOCUS = 30;
  public static final int FRAME = 191;
  public static final int ATTR_ASSIGN = 5;
  public static final int ALT = 123;
  public static final int SCHEME = 98;
  public static final int MEDIA = 104;
  public static final int PLUS = 203;
  public static final int LPAREN = 207;
  public static final int CLASS = 13;
  public static final int MAXLENGTH = 148;
  public static final int ALL = 168;
  public static final int AREA = 126;
  public static final int META = 90;
  public static final int VALUETYPE = 121;
  public static final int DEL = 62;
  public static final int HSIDES = 160;
  public static final int ACCEPT = 133;
  public static final int ACCEPT_CHARSET = 134;
  public static final int SELECT = 57;
  public static final int ABOVE = 158;
  public static final int HEADERS = 198;
  public static final int CODE = 46;
  public static final int ONDBLCLICK = 20;
  public static final int BOTTOM = 179;
  public static final int ROW = 195;
  public static final int TOP = 177;
  public static final int ADDRESS = 81;
  public static final int ONSELECT = 149;
  public static final int TFOOT = 183;
  public static final int ONMOUSEUP = 22;
  public static final int SUP = 55;
  public static final int TBODY = 184;
  public static final int LI = 74;
  public static final int FILE = 142;
  public static final int DATA = 113;
  public static final int WIDTH = 118;
  public static final int BDO = 34;
  public static final int SUB = 54;
  public static final int COORDS = 108;
  public static final int PROFILE = 93;
  public static final int ACRONYM = 53;
  public static final int DISABLED = 145;
  public static final int HREFLANG = 100;
  public static final int ISMAP = 125;
  public static final int CODETYPE = 114;
  public static final int POLY = 10;
  public static final int STRONG = 44;
  public static final int TEXT = 136;
  public static final int VAR = 50;
  public static final int ROWGROUP = 196;
  public static final int TABINDEX = 29;
  public static final int ONKEYUP = 27;
  public static final int FOR = 135;
  public static final int USEMAP = 119;
  public static final int READONLY = 146;
  public static final int RESET = 141;
  public static final int ONMOUSEOUT = 24;
  public static final int BOX = 164;
  public static final int HEIGHT = 117;
  public static final int STRING = 210;
  public static final int Q = 47;
  public static final int DATETIME = 106;
  public static final int SPAN = 33;
  public static final int P = 82;
  public static final int LINK = 91;
  public static final int RULES = 192;
  public static final int CODEBASE = 112;
  public static final int I = 39;
  public static final int XML_SPACE = 105;
  public static final int ROWSPAN = 200;
  public static final int B = 40;
  public static final int A = 65;
  public static final int SMALL = 42;
  public static final int ONBLUR = 31;
  public static final int LEGEND = 156;
  public static final int QUATATION_MARKS = 6;
  public static final int LONGDESC = 124;
  public static final int LANG = 15;
  public static final int NOHREF = 127;
  public static final int DECLARE = 110;
  public static final int error = 1;
  public static final int ENCTYPE = 130;
  public static final int ID = 12;
  public static final int UL = 72;
  public static final int DEFAULT = 11;
  public static final int ABBR = 52;
  public static final int COLS = 155;
  public static final int MULTIPLE = 151;
  public static final int SRC = 122;
  public static final int BUTTON = 60;
  public static final int CELLSPACING = 193;
  public static final int HR = 79;
  public static final int ONMOUSEDOWN = 21;
  public static final int TT = 38;
  public static final int TR = 187;
  public static final int OBJECT = 36;
  public static final int RECT = 8;
  public static final int JUSTIFY = 175;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPEN_TAG",
  "CLOSE_TAG",
  "OPEN_CLOSING_TAG",
  "ATTR_ASSIGN",
  "QUATATION_MARKS",
  "DOCTYPE",
  "RECT",
  "CIRCLE",
  "POLY",
  "DEFAULT",
  "ID",
  "CLASS",
  "STYLE",
  "LANG",
  "TITLE",
  "XML_LANG",
  "DIR",
  "ONCLICK",
  "ONDBLCLICK",
  "ONMOUSEDOWN",
  "ONMOUSEUP",
  "ONMOUSEMOVE",
  "ONMOUSEOUT",
  "ONKEYPRESS",
  "ONKEYDOWN",
  "ONKEYUP",
  "ACCESSKEY",
  "TABINDEX",
  "ONFOCUS",
  "ONBLUR",
  "BR",
  "SPAN",
  "BDO",
  "MAP",
  "OBJECT",
  "IMG",
  "TT",
  "I",
  "B",
  "BIG",
  "SMALL",
  "EM",
  "STRONG",
  "DFN",
  "CODE",
  "Q",
  "SAMP",
  "KBD",
  "VAR",
  "CITE",
  "ABBR",
  "ACRONYM",
  "SUB",
  "SUP",
  "INPUT",
  "SELECT",
  "TEXTAREA",
  "LABEL",
  "BUTTON",
  "INS",
  "DEL",
  "SCRIPT",
  "NOSCRIPT",
  "A",
  "H1",
  "H2",
  "H3",
  "H4",
  "H5",
  "H6",
  "UL",
  "OL",
  "LI",
  "DL",
  "DT",
  "DD",
  "PRE",
  "HR",
  "BLOCKQUOTE",
  "ADDRESS",
  "P",
  "DIV",
  "FIELDSET",
  "TABLE",
  "FORM",
  "HTML",
  "HEAD",
  "BODY",
  "META",
  "LINK",
  "BASE",
  "PROFILE",
  "HREF",
  "HTTPEQUIV",
  "NAME",
  "CONTENT",
  "SCHEME",
  "CHARSET",
  "HREFLANG",
  "TYPE",
  "REL",
  "REV",
  "MEDIA",
  "XML_SPACE",
  "DATETIME",
  "SHAPE",
  "COORDS",
  "PARAM",
  "DECLARE",
  "CLASSID",
  "CODEBASE",
  "DATA",
  "CODETYPE",
  "ARCHIVE",
  "STANDBY",
  "HEIGHT",
  "WIDTH",
  "USEMAP",
  "VALUE",
  "VALUETYPE",
  "SRC",
  "ALT",
  "LONGDESC",
  "ISMAP",
  "AREA",
  "NOHREF",
  "ACTION",
  "METHOD",
  "ENCTYPE",
  "ONSUBMIT",
  "ONRESET",
  "ACCEPT",
  "ACCEPT_CHARSET",
  "FOR",
  "TEXT",
  "PASSWORD",
  "CHECKBOX",
  "RADIO",
  "SUBMIT",
  "RESET",
  "FILE",
  "HIDDEN",
  "CHECKED",
  "DISABLED",
  "READONLY",
  "SIZE",
  "MAXLENGTH",
  "ONSELECT",
  "ONCHANGE",
  "MULTIPLE",
  "OPTGROUP",
  "OPTION",
  "ROWS",
  "COLS",
  "LEGEND",
  "VOID",
  "ABOVE",
  "BELOW",
  "HSIDES",
  "LHS",
  "RHS",
  "VSIDES",
  "BOX",
  "BORDER",
  "NONE",
  "GROUPS",
  "ALL",
  "CHAR",
  "CHAROFF",
  "ALIGN",
  "LEFT",
  "CENTER",
  "RIGHT",
  "JUSTIFY",
  "VALIGN",
  "TOP",
  "MIDDLE",
  "BOTTOM",
  "BASELINE",
  "CAPTION",
  "THEAD",
  "TFOOT",
  "TBODY",
  "COLGROUP",
  "COL",
  "TR",
  "TH",
  "TD",
  "SUMMARY",
  "FRAME",
  "RULES",
  "CELLSPACING",
  "CELLPADDING",
  "ROW",
  "ROWGROUP",
  "AXIS",
  "HEADERS",
  "SCOPE",
  "ROWSPAN",
  "COLSPAN",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "NUMBER",
  "STRING"
  };
}

